version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - OPENAI_API_KEY=$OPENAI_API_KEY
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"